### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rikkie80**
Updated sensors according to the new template integration. The old style is not recommended anymore!

### CODE REVIEW

**Comment by AcidSleeper** [comment]
Whats the reference to that?
Thanks.

**Comment by Rikkie80** [comment]
[https://www.home-assistant.io/integrations/template/](url)

**Comment by AcidSleeper** [comment]
EDIT:

I havent even seen that template before.
So that means that I should remove in configuration.yaml 

sensor: !include sensors.yaml 
and replace with 
template: include templates.yaml

and in templates.yaml start with 
sensor: 
and then your code?

**Comment by AcidSleeper** [comment]
Most of theese sensors that you have commited is not in my philips-integration.

Will upgrade to the new template but will not use merge.

**Comment by Rikkie80** [comment]
> EDIT:
> 
> I havent even seen that template before. So that means that I should remove in configuration.yaml
> 
> sensor: !include sensors.yaml and replace with template: include templates.yaml
> 
> and in templates.yaml start with sensor: and then your code?

Indeed. If you put it directly in configuration.yaml it looks like this:
```
template:
  - sensor:
      - unique_id: "purifier_air_quality"
        name: ....
```

**Pull request closed without merging**
